apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: {name: todos.rules-k8s.bazel.io}
spec:
  group: rules-k8s.bazel.io
  names: {kind: Todo, plural: todos, singular: todo}
  scope: Namespaced
  version: v1

---
apiVersion: rules-k8s.bazel.io/v1
kind: Todo
metadata: {name: my-todo1}
spec: {done: false, subject: Do something}

---
apiVersion: rules-k8s.bazel.io/v1
kind: Todo
metadata: {name: my-todo2}
spec: {done: false, subject: Do something}

---
apiVersion: rules-k8s.bazel.io/v1
kind: Todo
metadata: {name: my-todo3}
spec: {done: false, subject: Do something}

---
apiVersion: rules-k8s.bazel.io/v1
kind: Todo
metadata: {name: my-todo4}
spec: {done: false, subject: Do something}

---
apiVersion: rules-k8s.bazel.io/v1
kind: Todo
metadata: {name: my-todo5}
spec: {done: false, subject: Do something}

---
apiVersion: rules-k8s.bazel.io/v1
kind: Todo
metadata: {name: my-todo6}
spec: {done: false, subject: Do something}

---
apiVersion: rules-k8s.bazel.io/v1
kind: Todo
metadata: {name: my-todo7}
spec: {done: false, subject: Do something}

---
apiVersion: rules-k8s.bazel.io/v1
kind: Todo
metadata: {name: my-todo8}
spec: {done: false, subject: Do something}

---
apiVersion: rules-k8s.bazel.io/v1
kind: Todo
metadata: {name: my-todo9}
spec: {done: false, subject: Do something}

---
apiVersion: rules-k8s.bazel.io/v1
kind: Todo
metadata: {name: my-todo10}
spec: {done: false, subject: Do something}

